language: cpp

compiler:
  - clang

services: redis

# install pre-reqs
install:
  - sudo apt-get install libmsgpack-dev libboost-date-time-dev libboost-test-dev libboost-filesystem-dev libhiredis-dev

# Run the Build script
script:
  - mkdir _build
  - cd _build
  - cmake ..
  - sudo make install
  - sudo ldconfig

after_script:
  - REDIS_HOST="localhost" make test
