language: cpp

env:
  global:
    - secure: "bxF90B6O9OoW4AjDn7pQFuUvRb5RijmVdNLcW8NlLTh8wsnTQaRPNDH/ciu3qU47wC7bMWNsZVgeTyZIy6W5T5YDxDFcDBAFw4EvlXxskW2rF3AsqfpoZKuoOo1dZhAuekyZn29TRqHlG1OMTIFJ0zC4PgyKCfzgOBbBEtIutm0="

compiler:
  - gcc
  - clang

services: redis

# install pre-reqs
install:
  - sudo apt-get install libmsgpack-dev libboost-thread-dev libboost-date-time-dev libboost-test-dev libboost-filesystem-dev libboost-system-dev libhiredis-dev

# Run the Build script
script:
  - mkdir _build
  - cd _build
  - cmake ..
  - sudo make install
  - sudo ldconfig

after_script:
  - REDIS_HOST="localhost" make test

addons:
  coverity_scan:
    project:
      name: "luca3m/redis3m"
      description: "A C++ Redis client"
    notification_email: lucamarturana@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: coverity
