language: cpp

compiler:
  - clang

# install pre-reqs
install:
  - sudo apt-get install libmsgpack-dev libboost-regex-dev libboost-date-time-dev libboost-test-dev libboost-filesystem-dev libboost-system-dev libhiredis-dev

# Run the Build script
script:
  - cmake .
  - sudo make install
  - sudo ldconfig
  - bash ./run-tests.sh
